# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ManyToManyField(blank=True, default='', to='music.Label'),
        ),
    ]
