# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
    ]
