# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170724_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='file_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_format',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
