language: python

python:
  - "3.4"

env:
  global:
# - DJANGO="x.y.z"
  - DJANGO_SETTINGS_MODULE="audiad.settings"
  - MOZ_HEADLESS=1

#addons:
#  firefox: latest

#commands to install dependencies
install:
  - pip install -q Django==1.11
  - pip install -q -r requirements.txt

before_script:
  - python manage.py migrate --settings=audiad.settings --configuration=Dev

#command to run the test suite
script:
  - coverage run manage.py test audiad.music --settings=audiad.settings --configuration=Dev

after_success:
  - coverage report
  # https://coveralls.io/github/josh-privata/audiad
  - coveralls