language: python

python:
  - "3.4"

#commands to install dependencies
install:
  - pip install -q Django==1.11
  - pip install -q -r requirements.txt


#command to run the test suite
script:
  - python manage.py test