# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.CharField(blank=True, default='album', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tags',
            field=models.CharField(blank=True, default='artist', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='tags',
            field=models.CharField(blank=True, default='country', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='tags',
            field=models.CharField(blank=True, default='genre', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='tags',
            field=models.CharField(blank=True, default='label', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(blank=True, default='song', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='tags',
            field=models.CharField(blank=True, default='style', max_length=250, null=True),
        ),
    ]
